---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # These will modify code
      - id: trailing-whitespace
      - id: end-of-file-fixer

      # These will verify only
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: forbid-submodules

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-push
      - id: talisman-commit

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.0
    hooks:
      - id: commitizen
