---
- id: lotus
  name: Lotus Logstash Test Runner
  description: Run Logstash pipeline test cases
  entry: lotus
  always_run: true
  pass_filenames: false
  require_serial: true
  language: rust
  stages: ["pre-commit"]
