---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # These will modify code
      - id: trailing-whitespace
      - id: end-of-file-fixer

      # These will verify only
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-vcs-permalinks
      - id: forbid-submodules

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.37.0
    hooks:
      - id: talisman-push
      - id: talisman-commit

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.0
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: cargo-nextest
        name: Cargo Nextest
        entry: cargo nextest run
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-check
        name: Cargo Check
        entry: cargo check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-clippy
        name: Cargo Clippy (with warnings)
        entry: cargo clippy -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-fmt-check
        name: Cargo Format (check)
        entry: cargo fmt -- --check
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-commit]

      - id: cargo-clippy-fix
        name: Cargo Clippy
        entry: cargo clippy --fix
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]

      - id: cargo-fmt
        name: Cargo Format
        entry: cargo fmt
        pass_filenames: false
        language: system
        types: [rust]
        stages: [pre-push]
