[package]
name = "lotus"
description = "Logstash test runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.6"
bollard = "0.14"
clap = { version = "4", features = ["derive"] }
directories = "5"
futures-util = "0.3"
handlebars = { version = "4.3", features = ["rust-embed"] }
reqwest = { version = "0.11", features = ["json"] }
rust-embed = "6"
serde = "1"
serde_json = "1"
similar = "2"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
