[package]
name = "lotus"
description = "Logstash test runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bollard = "0.14"
clap = { version = "4", features = ["derive"] }
futures = "0.3"
futures-util = "0.3"
similar = "2"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
